# Setup
title: Minwoo Jung
description: Studying master course in RPM Lab, SNU. 
url: https://github.com/minwoo0611
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
instagram:
  username: minwo0_jung
  card: summary
logo: logo.png
social:
  name: Minwoo Jung
  links:
    - https://www.instagram.com/minwo0_jung/
    - https://github.com/minwoo0611
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Minwoo Jung
  url: https://github.com/minwoo0611/
  email: moonshot@snu.ac.kr
